---
- name: Note app using django
  hosts: localhost
  become: true

  tasks:
    - name: build docker image
      docker_image:
        path: /home/anjila/Desktop/django-notes-app
        name: noteapp
        tag: latest
        source: build

    - name: start docker container
      docker_container:
        name: nginx_container
        image: noteapp:latest
        state: started
